### ISSUE TITLE
Create specific names for persist operations.

### ISSUE THREAD

**Issue by rhys-vdw** [rhys-vdw/atlas#1]
**current**
`Mapper#save(...records)` updates or inserts records.
`Mapper#insert(...records)` inserts records.
`Mapper#update(...records)` updates rows matching records.
`Mapper#patch(attributes)` updates all matching rows.

**maybe**
`Mapper#save(...records)` -> updates or inserts records.
`Mapper#create(...records)` -> inserts records
`Mapper#update(...records)` or `#updateRows()` -> updates rows matching records.
`Mapper#updateColumns(attributes)` updates all matching rows.

**Comment by ricardograca** [comment]
Isn't `Mapper#updateColumns` more like a `Mapper#updateAll`? The description even says it. Personally, I think it's best to try to hide RDBMS specific nomenclature from the API, and "columns" is very RDBMS-y. Same goes for "updateRows".

**Comment by rhys-vdw** [comment]
I'm trying to use the following language:

 - **row** Actual row in database.
 - **column** Name of column in database.
 - **record** `Object` returned/accepted by `Mapper` representing row data.
 - **attribute** Name or value on record.

```js
People.updateAll({ id: 1, name: 'Ricardo' }, { id: 2, name: 'Rhys' })
  .then(updated =>
// update people set name='Ricardo' where id=1;
// update people set name='Rhys' where id=2;
```

```js
People.target({ id: 1, name: 'Ricardo' }, { id: 2, name: 'Rhys' })
  .updateColumns({ name: 'new name' })
  .then(updated =>
// update people set name='new name' where id in (1, 2);
```

The rationale of `updateColumns(attributes)`  is that you're passing *attributes* (whose keys and values are optionally converted via mechanisms similar to `format` in Bookshelf). These column values are then used to update the database *columns*.

Typically a user would prefer to use `save()` instead of `update()`. Passing a bunch of records with ID values to `save()` is the same as passing them to `update()` or `updateAll()`.

I agree that the word "update" is overloaded here by being shared between saving *records* and calling an SQL `UPDATE`. I just can't think of a better word yet (hence the issue). Suggestions welcome. :)

**Comment by ricardograca** [comment]
Didn't know there was already a `updateAll`. The purpose of `target` is to create new models? Or is it the way to constrain the query?

Maybe it's best to assume that anyone using this will have some knowledge of SQL then, otherwise `updateColumns` and `updateRows` could become confusing :) 

Do you think it would be too confusing to just have one `update`? That is, it could take either a single model, several of them or an array and perform the actions according to that? Example:

```js
People.update({ id: 1, name: 'Ricardo' })
  .then(updated => ... )

People.update({ id: 1, name: 'Ricardo' }, { id: 2, name: 'Rhys' })
  .then(updated => ... )

People.update([{ id: 1, name: 'Ricardo' }, { id: 2, name: 'Rhys' }])
  .then(updated => ... )

// and then

People.updateAll({ name: 'new name' })
  .then(updated => ... )
// this one would update all People with the new name...
```

OTOH, if a user would just call `save()` anyway, what's the point of exposing `update()`? What would you be able to do with it that you wouldn't with `save()` alone?

**Comment by rhys-vdw** [comment]
> Didn't know there was already a updateAll.

Oops meant `update`. It does exist but it is the same as `update` actually. It's just an implementation detail, but to clarify it works like this currently:

```js
update(...records) {
  return isSingleRecord(...records)
    ? this.updateOne(...records)
    : this.updateAll(...records);
}
```

> OTOH, if a user would just call save() anyway, what's the point of exposing update()? What would you be able to do with it that you wouldn't with save() alone?

Right. Good point. There are two times when you might choose `update` instead of `save`, but neither is particularly important.

 - You have a function that is meant to `update` (not `insert`) a row, and you want an error to be fired if the ID is not supplied.
 - You prefer the slightly faster execution of skipping to step that groups all the records by new/not new before passing them to `update`/`insert`.

Perhaps I'll drop `update` because it's too ambiguous and have `updateRecords` and `updateAll` instead.

So:

```js
// public
Mapper.save(...records) // updates or inserts records.
Mapper.updateAll(attributes) // updates all matching rows.

// private (you can just use `save()` for these)
Mapper.insert(...records) // inserts records
Mapper.updateRecords(...records) // updates rows matching records.
```

Not having an `update` will help reduce the likelihood of this happening:
```js
cont user = { id: 5, name: 'new name' };
Users.update(user).then(result =>
// accidentally changed every row in the database!
````

**Comment by rhys-vdw** [comment]
btw, decided on your suggestion @ricardograca:

```js
Mapper.update(...records)
Mapper.updateAll(attributes)
```

Just got to double check that everything is as intended before closing this issue.

**Comment by ricardograca** [comment]
Cool :) :+1:

**Comment by rhys-vdw** [comment]
This seems to all be done.
